### ISSUE TITLE
PDF files may cause the application to hang or crash

### ISSUE THREAD

**Issue by 2HDFloppyDisk** [Natestah/BlitzSearch#10]
Searching .pdf files for keywords, in some instances, results in intermittent application hangs (while scrolling through the file) or randomly crashing (no error / dump info generated)

**Comment by Natestah** [comment]
Pdfs are classified as binary for now.  Maybe a later date I'll target some specific types for conversion to text (rtf,pdf,doc) mostly focused on text code types

**Comment by Natestah** [comment]
I also believe that the symptom of crashing due to large binary files is resolved with recent truncated result line length
