### ISSUE TITLE
Run from command line

### ISSUE THREAD

**Issue by kaste** [Natestah/BlitzSearch#104]
If you start blitz.exe from command line it should set the root/working dir space to the cwd.  (Maybe `blitz .` too.)  

This is unfortunately not supported at all, as blitz won't even focus if it already runs.  And if it doesn't run, it opens-as-closed ("hot-exit").

**Comment by Natestah** [comment]
Are you looking for automatic creation of the search scope when running blitz search with a command line.  A lot of this I am trying to do with the Extensions themselves.  For example if you open a workspace in VS Code, Blitz Search will pick that up and set a context.

**Comment by kaste** [comment]
I think so.  I might search for something that is explicitly not already open in my editor.  If you support `blitz .` from the command line, I could also add an entry to the context menu for Windows explorer.  The search within explorer is notoriously unusable slow.   And if I already have blitz installed ... why not use it for all the things?  

For bigger projects; I tend to only open a sub-project, sub-structures of it in my editor to keep it more compact.

**Comment by Natestah** [comment]
in version 0.0.89 I have added a -find switch.   This should work with either a running or new instance.

**Comment by kaste** [comment]
Haha, that already works very well.  For the explorer right click (context) menu, I would need a way to pass the selected folder to the command though.  Typical form is:

![image](https://github.com/user-attachments/assets/dc574e53-1435-43a8-9004-f9b54e769689)

Otherwise it starts the search from C:\windows\system32  😜

**Comment by Natestah** [comment]
I did this through the file context menu and figured it was the same. I didn't need the %1 since working directory was enough.

I'll have to look at it more.

**Comment by kaste** [comment]
Would be also nice if -- instead of the static "Explorer" -- it would tell the base name of the used path.  

https://github.com/Natestah/BlitzSearch/blob/a7e621fcce3712e4ace78114ebfae4c39de82d94/src/Blitz.Avalonia.Controls/Views/ExternalPluginInteractions.cs#L53

`Path.GetFileName(text)` irrc.

**Comment by Natestah** [comment]
Good grief.. I got this to work properly after fumbling around much.. requires v 0.0.91, just close and restart Blitz Search to update.

![image](https://github.com/user-attachments/assets/98004431-7b62-4638-898a-c21c4696b64a)

**Comment by kaste** [comment]
Yeah, works for me.  👍 Still says "Explorer" though :grin:

**Comment by Natestah** [comment]
I have that working, just ran out of time. I'm hoping to get to your other issue with global git ignores when I get some more free time. Thank you for your contribution!

**Comment by kaste** [comment]
The git-ignores-stuff is tricky...
