### ISSUE TITLE
Extensions support should include wildcard searches [Suggestion]

### ISSUE THREAD

**Issue by 2HDFloppyDisk** [Natestah/BlitzSearch#12]
The Extensions section only seems to support specific file extensions to search for. This requires a user to know what files they want to search through. In some cases, it would be helpful to use a wildcard (*) to search for any files in a given directory that contain the keyword of interest.

![image](https://github.com/Natestah/BlitzSearch/assets/56527482/2d587166-9f60-4e3b-aebf-cd5c2618d6a4)

**Comment by Natestah** [comment]
Wildcard is no longer needed. Everything is searched.  Users can use the filename filter to isolate the search from there
