### ISSUE TITLE
Search results cannot be updated unless toggling "Paths" options

### ISSUE THREAD

**Issue by 2HDFloppyDisk** [Natestah/BlitzSearch#15]
![image](https://github.com/Natestah/BlitzSearch/assets/56527482/cf69a79e-ba10-49dd-b0cc-3479ea5531b4)

Changing the search criteria (word or file name) doesn't trigger an update of the search. Instead, it seems there is a need to update the "Paths" options to trigger the search update. Also attempted to use enter key in those input fields with no success.

Maybe a SEARCH button would help here?

**Comment by Natestah** [comment]
There is no need for a search button. It updates correctly now
